name : CJ Jessett
brand : My Site
description : This is the description of my site
keyword : 
url : http://cjessett.github.io/jekyll

email : cjessett@gmail.com
instagram : cjessett
linkedin : cjessett
github : cjessett

author : CJ Jessett

analytics : UA-8418273-8

year : 2016

markdown : kramdown
exclude :
  - node_modules
