name : CJ Jessett
brand : My Site
description : This is my personal website
keyword : cj, jessett, cjessett
url : http://cjessett.github.io/jekyll

email : me@cjjessett.com
instagram : cjessett
linkedin : cjessett
github : cjessett
twitter : kep20f

author : CJ Jessett

analytics : UA-8418273-8

year : 2016

markdown : kramdown
exclude :
  - node_modules
